---
- hosts: webgroup
  become: yes
  become_user: root
  become_method: sudo

  tasks:
   - name: Nginx setup
     yum: pkg=nginx state=latest update_cache=true

   - name: Start Nginx
     service: name=nginx state=started

   - name: index.html copy
     template: src=example.html.j2 dest=/usr/share/nginx/html/index.html
